all: informe-primera-entrega

informe-primera-entrega: informe-primera-entrega
	pdflatex informe-primera-entrega.tex
	pdflatex informe-primera-entrega.tex
	pdflatex informe-primera-entrega.tex

view:
	zathura informe-primera-entrega.pdf

open:
	make && make view

clean:
	rm -f *.aux *.log *.synctex.gz *.out *.xml *.bcf *.blg *.bbl *.toc
